# permissions for end users to edit argohelmreposecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: argohelmreposecret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ecr-secret-operator
    app.kubernetes.io/part-of: ecr-secret-operator
    app.kubernetes.io/managed-by: kustomize
  name: argohelmreposecret-editor-role
rules:
- apiGroups:
  - ecr.mobb.redhat.com
  resources:
  - argohelmreposecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ecr.mobb.redhat.com
  resources:
  - argohelmreposecrets/status
  verbs:
  - get
