apiVersion: ecr.mobb.redhat.com/v1alpha1
kind: ArgoHelmRepoSecret
metadata:
  labels:
    app.kubernetes.io/name: argohelmreposecret
    app.kubernetes.io/instance: argohelmreposecret-sample
    app.kubernetes.io/part-of: ecr-secret-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ecr-secret-operator
  name: argohelmreposecret-sample
spec:
  # TODO(user): Add fields here
